import { User, Translation, Quiz, QuizResult, Badge, Document } from './types';

export const mockBadges: Badge[] = [
  {
    id: 'badge-1',
    name: 'First Translation',
    description: 'Completed your first translation',
    icon: '🎯',
    earnedAt: '2025-10-01',
  },
  {
    id: 'badge-2',
    name: 'Quiz Master',
    description: 'Completed 5 quizzes',
    icon: '🏆',
    earnedAt: '2025-10-05',
  },
  {
    id: 'badge-3',
    name: 'Language Explorer',
    description: 'Translated in both languages',
    icon: '🌍',
    earnedAt: '2025-10-03',
  },
];

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Demo User',
    email: 'demo@transly.com',
    role: 'general',
    points: 1250,
    rank: 1,
    quizzesCompleted: 8,
    translationsCount: 25,
    badges: mockBadges,
  },
  {
    id: 'user-2',
    name: 'Sarah Johnson',
    email: 'sarah@transly.com',
    role: 'general',
    points: 980,
    rank: 2,
    quizzesCompleted: 6,
    translationsCount: 18,
    badges: [mockBadges[0], mockBadges[1]],
  },
  {
    id: 'user-3',
    name: 'Raj Patel',
    email: 'raj@transly.com',
    role: 'educator',
    points: 850,
    rank: 3,
    quizzesCompleted: 5,
    translationsCount: 15,
    badges: [mockBadges[0]],
  },
  {
    id: 'user-4',
    name: 'Admin User',
    email: 'admin@transly.com',
    role: 'admin',
    points: 0,
    rank: 0,
    quizzesCompleted: 0,
    translationsCount: 0,
    badges: [],
  },
  {
    id: 'user-5',
    name: 'Maya Silva',
    email: 'maya@transly.com',
    role: 'general',
    points: 720,
    rank: 4,
    quizzesCompleted: 4,
    translationsCount: 12,
    badges: [mockBadges[0]],
  },
];

export const mockTranslations: Translation[] = [
  {
    id: 'trans-1',
    userId: 'user-1',
    sourceLanguage: 'nepali',
    targetLanguage: 'english',
    sourceText: 'म स्कूल जान्छु',
    translatedText: 'I go to school',
    timestamp: '2025-10-09T10:30:00Z',
    isFavorite: true,
  },
  {
    id: 'trans-2',
    userId: 'user-1',
    sourceLanguage: 'nepali',
    targetLanguage: 'english',
    sourceText: 'तपाईंलाई कस्तो छ?',
    translatedText: 'How are you?',
    timestamp: '2025-10-09T09:15:00Z',
    isFavorite: false,
  },
  {
    id: 'trans-3',
    userId: 'user-1',
    sourceLanguage: 'sinhalese',
    targetLanguage: 'english',
    sourceText: 'මම පාසලට යනවා',
    translatedText: 'I am going to school',
    timestamp: '2025-10-08T14:20:00Z',
    isFavorite: true,
  },
  {
    id: 'trans-4',
    userId: 'user-1',
    sourceLanguage: 'nepali',
    targetLanguage: 'english',
    sourceText: 'यो किताब धेरै राम्रो छ',
    translatedText: 'This book is very good',
    timestamp: '2025-10-07T11:45:00Z',
    isFavorite: false,
  },
  {
    id: 'trans-5',
    userId: 'user-1',
    sourceLanguage: 'sinhalese',
    targetLanguage: 'english',
    sourceText: 'ඔබට කෙසේද?',
    translatedText: 'How are you?',
    timestamp: '2025-10-06T16:30:00Z',
    isFavorite: false,
  },
];

export const mockQuizzes: Quiz[] = [
  {
    id: 'quiz-1',
    title: 'Nepali Basics - Greetings',
    language: 'nepali',
    difficulty: 'easy',
    points: 100,
    questions: [
      {
        id: 'q1',
        type: 'multiple-choice',
        question: 'Translate to English: "नमस्ते"',
        options: ['Hello', 'Goodbye', 'Thank you', 'Please'],
        correctAnswer: 'Hello',
        points: 20,
      },
      {
        id: 'q2',
        type: 'multiple-choice',
        question: 'Translate to English: "धन्यवाद"',
        options: ['Please', 'Sorry', 'Thank you', 'Welcome'],
        correctAnswer: 'Thank you',
        points: 20,
      },
      {
        id: 'q3',
        type: 'fill-blank',
        question: 'Translate to English: "म ठीक छु"',
        correctAnswer: 'I am fine',
        points: 30,
      },
      {
        id: 'q4',
        type: 'multiple-choice',
        question: 'Translate to English: "तपाईंको नाम के हो?"',
        options: ['What is your name?', 'Where are you?', 'How old are you?', 'What time is it?'],
        correctAnswer: 'What is your name?',
        points: 30,
      },
    ],
  },
  {
    id: 'quiz-2',
    title: 'Sinhalese Daily Conversations',
    language: 'sinhalese',
    difficulty: 'medium',
    points: 150,
    questions: [
      {
        id: 'q5',
        type: 'multiple-choice',
        question: 'Translate to English: "ආයුබෝවන්"',
        options: ['Hello', 'Goodbye', 'Good night', 'Good morning'],
        correctAnswer: 'Hello',
        points: 25,
      },
      {
        id: 'q6',
        type: 'multiple-choice',
        question: 'Translate to English: "ස්තූතියි"',
        options: ['Sorry', 'Thank you', 'Please', 'Excuse me'],
        correctAnswer: 'Thank you',
        points: 25,
      },
      {
        id: 'q7',
        type: 'fill-blank',
        question: 'Translate to English: "මම හොඳින් ඉන්නවා"',
        correctAnswer: 'I am fine',
        points: 50,
      },
      {
        id: 'q8',
        type: 'multiple-choice',
        question: 'Translate to English: "ඔබේ නම කුමක්ද?"',
        options: ['What is your name?', 'How are you?', 'Where do you live?', 'What do you do?'],
        correctAnswer: 'What is your name?',
        points: 50,
      },
    ],
  },
  {
    id: 'quiz-3',
    title: 'Nepali Numbers and Time',
    language: 'nepali',
    difficulty: 'hard',
    points: 200,
    questions: [
      {
        id: 'q9',
        type: 'multiple-choice',
        question: 'Translate to English: "एक, दुई, तीन"',
        options: ['One, two, three', 'Four, five, six', 'Seven, eight, nine', 'Ten, eleven, twelve'],
        correctAnswer: 'One, two, three',
        points: 40,
      },
      {
        id: 'q10',
        type: 'fill-blank',
        question: 'Translate to English: "अहिले कति बज्यो?"',
        correctAnswer: 'What time is it now?',
        points: 60,
      },
    ],
  },
];

export const mockQuizResults: QuizResult[] = [
  {
    id: 'result-1',
    userId: 'user-1',
    quizId: 'quiz-1',
    score: 90,
    totalPoints: 100,
    completedAt: '2025-10-08T10:00:00Z',
    answers: [],
  },
  {
    id: 'result-2',
    userId: 'user-1',
    quizId: 'quiz-2',
    score: 125,
    totalPoints: 150,
    completedAt: '2025-10-07T15:30:00Z',
    answers: [],
  },
  {
    id: 'result-3',
    userId: 'user-1',
    quizId: 'quiz-3',
    score: 180,
    totalPoints: 200,
    completedAt: '2025-10-06T12:00:00Z',
    answers: [],
  },
];

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    userId: 'user-1',
    name: 'Sample_Nepali_Document.pdf',
    type: 'pdf',
    uploadedAt: '2025-10-08T09:00:00Z',
    sourceLanguage: 'nepali',
    originalText: 'नमस्ते, यो एक नमूना कागजात हो।',
    translatedText: 'Hello, this is a sample document.',
    status: 'completed',
  },
  {
    id: 'doc-2',
    userId: 'user-1',
    name: 'Sinhalese_Text_Image.jpg',
    type: 'image',
    uploadedAt: '2025-10-07T14:30:00Z',
    sourceLanguage: 'sinhalese',
    originalText: 'ආයුබෝවන්, මෙය නියැදි පෙළකි.',
    translatedText: 'Hello, this is sample text.',
    status: 'completed',
  },
  {
    id: 'doc-3',
    userId: 'user-1',
    name: 'Research_Notes.docx',
    type: 'docx',
    uploadedAt: '2025-10-06T11:15:00Z',
    sourceLanguage: 'nepali',
    originalText: 'अनुसन्धान नोटहरू',
    translatedText: 'Research notes',
    status: 'completed',
  },
];

// Mock translation function
export const mockTranslate = (text: string, sourceLang: 'nepali' | 'sinhalese'): string => {
  const translations: Record<string, string> = {
    'म स्कूल जान्छु': 'I go to school',
    'तपाईंलाई कस्तो छ?': 'How are you?',
    'नमस्ते': 'Hello',
    'धन्यवाद': 'Thank you',
    'म ठीक छु': 'I am fine',
    'तपाईंको नाम के हो?': 'What is your name?',
    'यो किताब धेरै राम्रो छ': 'This book is very good',
    'म तिमीलाई माया गर्छु': 'I love you',
    
    'මම පාසලට යනවා': 'I am going to school',
    'ඔබට කෙසේද?': 'How are you?',
    'ආයුබෝවන්': 'Hello',
    'ස්තූතියි': 'Thank you',
    'මම හොඳින් ඉන්නවා': 'I am fine',
    'ඔබේ නම කුමක්ද?': 'What is your name?',
  };

  return translations[text] || `Translated: ${text}`;
};
